project_id = "tnjdzvajwmtxtsawhkab"

[functions.calculate-delivery]
verify_jwt = false

[functions.lookup-cep]
verify_jwt = false

[functions.create-pix-payment]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.create-order]
verify_jwt = false

[functions.build-whatsapp-message]
verify_jwt = false

[functions.delete-order]
verify_jwt = false
